version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:8.0'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      #      POSTGRES_DB: ${POSTGRES_DB:-app}
      #      # You should definitely change the password in production
      #      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      #      POSTGRES_USER: ${POSTGRES_USER:-app}
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bet_analyzer
      MYSQL_USER: bet_analyzer
      MYSQL_PASSWORD: 123Katzen
    volumes:
      - db-data:/home/wolfgang/Documents/programming/DB
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - '3306:3306'
###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
